### ISSUE TITLE
Login page styling is broken

### ISSUE THREAD

**Issue by noliveleger** [mirror-effect-plus-protocol/mepp-web#31]
A new div wrapper is present with React-Admin 4.x `MuiScopedCssBaseline-root`
This div contains admin CSS which overrides the login page and all other pages inside patient app.

![Production](https://github.com/mirror-effect-plus-protocol/mepp-web/assets/24226825/35e9e2d3-e379-4adb-98ed-d7655c4507a6)

![Dev](https://github.com/mirror-effect-plus-protocol/mepp-web/assets/24226825/68d83625-2126-4ee0-bba8-88a3c255c4d3)

**Comment by fperreault** [comment]
fixed
