### ISSUE TITLE
Add `staging` banner to admin interface

### ISSUE THREAD

**Issue by noliveleger** [mirror-effect-plus-protocol/mepp-web#46]
`<EnvironmentBanner />` does not show up when logged as staff user in the admin interface.

**Comment by fperreault** [comment]
fixed with: [05e8e0f83ea2b14b5a1e8ecf9746e492387018ac](https://github.com/mirror-effect-plus-protocol/mepp-web/commit/05e8e0f83ea2b14b5a1e8ecf9746e492387018ac)
