### ISSUE TITLE
problems to reset password for first timers

### ISSUE THREAD

**Issue by Sarmar57** [mirror-effect-plus-protocol/mepp-web#9]
@noliveleger 
2 users, one patient and one clinician reported this problem: 
the password reset link just takes me back to the main page, and  and then if I put a password in it tells, me it is invalid. 
I think this could be corrected by writing in the welcoming email that the NEW password should contain 8 characters, capital and small letters, a number, and a special character

**Comment by Sarmar57** [comment]
It works also for me, this is why I think the problem comes from the fact that they enter invalid passwords that do not correspond to our criteria. If you could modify both texts (fr + eng) of the welcoming email, that should be ok

**Comment by noliveleger** [comment]
Ah ok! 
FYI: It is not possible to save an invalid password. It would not pass the validation. 

Let's add the criteria to the welcoming e-mail as you suggest.

**Comment by noliveleger** [comment]
Closing this in favor of #15. When accessing the reset-password form, the password requirements are correctly displayed.
